services:
  nginx:
    image: nginx:1.27.5-alpine
    container_name: mynginx
    ports:
      - "8085:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf