# networks:
#   todo-net:
#     name: todo-net
#     driver: bridge

services:
  app1:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app1
    platform: linux/arm64
    environment:
      DB_TYPE: mariadb
      NEXT_PUBLIC_BASE_PATH: /app1
      MARIADB_HOST: mariadb
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_PORT: 3306
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - database-net

  app2:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app2
    platform: linux/arm64
    environment:
      DB_TYPE: postgres
      NEXT_PUBLIC_BASE_PATH: /app2
      POSTGRES_HOST: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: todo_app
      POSTGRES_PORT: 5432
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - database-net

  app3:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app3
    platform: linux/arm64
    environment:
      DB_TYPE: mongo
      NEXT_PUBLIC_BASE_PATH: /app3
      MONGO_HOST: todo-mongo
      MONGO_USER: todo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: todo_app
      MONGO_PORT: 27017
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - database-net

networks:
  database-net:
    external: true