services:
  app1:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app1
    restart: unless-stopped
    networks:
      - todo-net

  app2:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app2
    restart: unless-stopped
    networks:
      - todo-net

  app3:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app3
    restart: unless-stopped
    networks:
      - todo-net

networks:
  todo-net:
    external: true