services:
  app1:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app1
    environment:
      DB_TYPE: mariadb
      NEXT_PUBLIC_BASE_PATH: /app1

      MARIADB_HOST: mariadb
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_PORT: 3306

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

  app2:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app2
    environment:
      DB_TYPE: postgres
      NEXT_PUBLIC_BASE_PATH: /app2

      POSTGRES_HOST: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: todo_app
      POSTGRES_PORT: 5432

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

  app3:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app3
    environment:
      DB_TYPE: mongo
      NEXT_PUBLIC_BASE_PATH: /app3

      MONGO_HOST: mongo
      MONGO_USER: todo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: todo_app
      MONGO_PORT: 27017

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

networks:
  todo-net:
    external: true