services:
  app1:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app1
    ports:
      - "3001:3000"
    environment:
      # mariadb / postgres / mongo
      DB_TYPE: mongo

      MARIADB_HOST: mariadb
      MARIADB_USER: 
      MARIADB_PASSWORD: 
      MARIADB_DATABASE: 
      MARIADB_PORT: 3306

      POSTGRES_HOST: postgres
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DATABASE: 
      POSTGRES_PORT: 5432

      MONGO_HOST: mongo
      MONGO_USER: 
      MONGO_PASSWORD: 
      MONGO_DATABASE: 
      MONGO_PORT: 27017

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - database-net

networks:
  database-net:
    external: true
