services:
  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    depends_on:
      - loki
    networks:
      - database-net

  app1:
    image: xtaoi/todo-app:v1.0.0-next
    container_name: app1
    ports:
      - "3001:3000"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: app1
    environment:
      DB_TYPE: postgres

      MARIADB_HOST: mariadb
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_PORT: 3306

      POSTGRES_HOST: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: todo_app
      POSTGRES_PORT: 5432

      MONGO_HOST: mongo
      MONGO_USER: todo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: todo_app
      MONGO_PORT: 27017

      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      - fluent-bit
      - loki
    networks:
      - database-net
      
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - database-net

volumes:
  loki-data:

networks:
  database-net:
    external: true