networks:
  database-net:
    name: database-net

services:
  mariadb:
    image: mariadb:12.1.2
    container_name: todo-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
    #   - mariadb_data:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - database-net

  postgres:
    image: postgres:18.1
    container_name: todo-postgres
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
    #   - postgres_data:/var/lib/postgresql
      - ./init/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - database-net

  mongo:
    image: mongo:8.2.3
    container_name: todo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo_app
    ports:
      - "27017:27017"
    volumes:
    #   - mongo_data:/data/db
      - ./init/mongo:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - database-net

# volumes:
#   mariadb_data:
#   postgres_data:
#   mongo_data:
