services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f fluentd > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: busybox
    container_name: demo-app
    command: >
      sh -c "while true; do
      echo '{\"service\":\"demo-app\",\"msg\":\"hello fluentd\",\"level\":\"INFO\"}';
      sleep 2;
      done"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: demo.app
    depends_on:
      fluentd:
        condition: service_healthy
